name: cd

on:
  push:
    branches: [main]

jobs:
  Deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    # Check out the code from the repository prebuilt action
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Node
      # Set up Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build
